### PR TITLE
SQL_DCL_HW

### PR DESCRIPTION
**Pull request by dncsilla**

### CODE REVIEW

**Review by glybinahanna — CHANGES_REQUESTED** [review]
Great job! Please see comments:
- script is not rerunable. If rentaluser already exists the script will fail. Same for rental role.
- ids shouldn't be hardcoded for INSERT and UPDATE queries.


**Not approved, please make changes based on the feedback.**

**Comment by dncsilla** [comment]
Thank you for the review! 
Based on the review, the rerunnability of the creation of roles and the hardcoding of id's in relation to INSERT and UPDATE was updated.

**Review by glybinahanna — CHANGES_REQUESTED** [review]
Great job! Please see comment:
- ids are still hardcoded in task 5.

**Not approved, please make changes based on the feedback.**

**Comment by dncsilla** [comment]
Hi Hanna, Thank you ! Earlier I have not updated the task 5 hardcoding, simply beacuse I thought that it is for testing whether the permission is denied. Now it is updated :)

**Review by glybinahanna — APPROVED** [review]
Hi! Thank you :) **Approved. Please merge.**

**Pull request merged**
